- name: Install and Run nginx #name is not mandatory,this is best practice 
  Host: Mongodb
  become: yes #this will give us root access.
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: 
      ansible.builtin.service:
        name: nginx
        state: started