- name: variables from files
  hosts: localhost #Managing the ansible server itself
  vars_files: 
  - variables.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "Hello, i'm learning {{NAME}}, and the trainer is {{TRAINER}}, with time tenure of {{DURATION}}"