- name: variables at task level #Here there is simple level of inheritence.
  hosts: localhost
  #These are play level vars
  vars:
  - money: "1000rs"
    land: "100 hc"
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: Inheriting the values from play and add and overridex
    vars: #these are task level vars
    - money: "1999 rs"
      houses: "10000 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"




#genrally we know what is inheritence.
# Father ----> earned some property
# children ---> by default they inherit the property
# chilren can change the value of property
# You inherit the values from parent, as a children you can override the values, you can add the values.




















