- name: variables at task level #Here there is simple level of inheritence.
  hosts: localhost
  #These are play level vars
  vars:
  - money: "1000rs"
    land: "100 hc"
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  vars: #these are task level vars
  - money: "1999 rs"
    houses: "10000 houses"
  tasks: 
  - name: printing variables
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"




















