- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: Sai arun yadav-playlevel
  vars_files:
    - variable.yaml
  vars_prompt
    - name: NAME
      prompt: please enter your username
      private: false
  tasks: 
  - name: variable at task level 
    vars:
      NAME: saiarun-tasklevel
      ansible.bulitin.debug:
      msg: "Trainer name is: {{NAME}}"
