- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: Saiarunyadav-playlevel
  vars_files:
  - variable.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter your Trainer name
    private: false
  tasks: 
  - name: variable at task level 
    vars:
      NAME: saiarun-tasklevel
    ansible.builtin.debug:
      msg: "Trainer name is: {{NAME}}"


# preferences
# 1. command line variable
# 2. task level
# 3. Vars_files
# 4. vars_Promt
# 5. Playlevel
# 6. inventory
# 7. Roles (This is will said while discussing about the roles)