- name: create user 
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not 
    # 1) when you want to run linux commands directly i.e in the case ansible module not available
    # when the user does not exists, ansible treating this failure and come out by "DEFAULT"
    # ignore_errors: true
    ansible.builtin.command: id roboshop   #(1)Here ansible will run this command and store the output in (register)
    register: output #output is variable name (we can give any name here)
    ignore_errors: true  #(This is expected error so we inform the ansible to ignore it)
  - name: print the command output 
    ansible.builtin.debug:
      msg: "output is: {{output}}"
  - name: print exit status 
    ansible.builtin.debug:
      msg: "{{output.rc}}" #-----------> rc Means EXIT STATUS IN ANSIBLE (Here we need RC in the whole output mentioned below)
   # here we got it rc as 1 now BAING UPON THIS WE WILL WRITE A CODITION.
  - name: create user roboshop # In ansible the condition will be as "WHEN"
    become: yes #here this will run only for task level
    ansible.builtin.user: # if the user doesn't exist then this will run
      name: roboshop
    when: output.rc != 0








# NOTE :- Ansible will default comes out if the task is fail.



    # {'changed': True,
    #  'stdout': '',
    #   'stderr': 'id: ‘roboshop’: no such user',
    #    'rc': 1, --------------------------------------------------------------------> "EXIT STATUS"
    #  'cmd': ['id', 'roboshop'],
    #   'start': '2023-11-11 15:44:28.010677', 
    #   'end': '2023-11-11 15:44:28.017786',
    #    'delta': '0:00:00.007109',
    #     'failed': True,
    #      'msg': 'non-zero return code',
    #       'stdout_lines': [],
    #        'stderr_lines': ['id: ‘roboshop’: no such user']}"

