#Take username as variable , and then dynamically check exists or not then create.

- name: assignment
  hosts: localhost
  vars: 
    USERNAME: Saiarun 
tasks:
  - name: run this if name is DevOps  #This module will run 
    ansible.builtin.debug:
      msg: "Hello {{USERNAME}}"
    when: USERNAME == "Saiarun" 

  